"""Constants for the Aereco Ventilation System integration."""

DOMAIN = "aereco_ventilation"
VERSION = "1.1.8"

# Default values
DEFAULT_PORT = 80
DEFAULT_UPDATE_INTERVAL = 30

# API Commands (from cst.js)
# GET Commands
GET_WARNINGS = "00"
GET_DEBUG_DATA = "01"  
GET_CURR_OPMODE = "02"
GET_OPERATION_MODES_CONFIG = "03"
GET_SETPOINT_VALUES = "04"
GET_MAINTENANCE_SECTION = "05"
GET_SENSORS = "06"
GET_WIZARD_CMD = "07"
GET_DATETIME = "08"
GET_TRAFIC_METERING = "09"
GET_WIFI_STATE = "10"
GET_DXRVERS = "11"
GET_LANGUAGE = "12"
GET_TEMPERATURE_UNIT = "13"
GET_HUBTYPE = "14"
GET_INSTALLED_DEVS = "15"
GET_EMAIL_ENABLED = "17"
GET_WIZARD_DONE = "18"
GET_WIFI_CFG = "19"
GET_SENS_ROOM_TUBE_LEN = "20"
GET_SENS_OF_ROOM = "21"
GET_ENERGY_GRAPH_DAILY = "22"
GET_ENERGY_GRAPH_MONTHLY = "23"
GET_ENERGY_GRAPH_YEARLY = "24"
GET_ANNEXES_PARAMS = "25"
GET_INSTALL_TIME = "26"
GET_APLIST0 = "27"
GET_ROOM_NAME1 = "43"
GET_SMTP_FROM = "53"
GET_SMTP_TO1 = "54"
GET_SMTP_TO2 = "55"
GET_WIFI_TIMESTAMP_FVESP = "56"
GET_AP_SSID = "57"
GET_STA_SSID = "58"
GET_ABOUT_INFO = "59"

# POST Commands
POST_FILTER_CHANGE_WARN = "0"
POST_AUTOMATIC_MODE_AIRFLOW = "1"
POST_FREE_COOLING_MODE_TIMEOUT = "2"
POST_FREE_COOLING_MODE_AIRFLW = "3"
POST_BOOST_MODE_TIMEOUT = "4"
POST_BOOST_MODE_AIRFLOW = "5"
POST_ABSENCE_MODE_TIMEOUT = "6"
POST_ABSENCE_MODE_AIRFLOW = "7"
POST_STOP_MODE_TIMEOUT = "8"
POST_STOP_MODE_AIRFLOW = "9"
POST_SET_POINT_KFACT_FANS = "10"
POST_SET_POINT_AIRFLOW_CLOGGED = "11"
POST_SET_POINT_TPREHEATER = "12"
POST_SET_POINT_EXHAUST_PRES = "13"
POST_SET_POINT_PREHEATERP = "14"
POST_CURRENT_MODE = "15"
POST_FILTER_RESET = "16"
POST_FILTER_TEST = "17"
POST_DEBUG_MODE = "18"
POST_PWM_EX = "19"
POST_PWM_SF = "20"
POST_STEP_BYPASS_VALVE = "21"
POST_STEP_EXHAUST_VALVE = "22"
POST_STEP_VALVE1 = "23"
POST_KEEP_ALIVE = "33"
POST_PWM_DF = "34"
POST_WIZARD_CMD = "35"
POST_DATE_TIME = "36"
POST_WIFI_STATE = "37"
POST_LANGUAGE = "38"
POST_TEMPERATURE_UNIT = "39"

# Operation Modes
MODE_AUTOMATIC = "0"
MODE_FREE_COOLING = "1"
MODE_BOOST = "2"
MODE_ABSENCE = "3"
MODE_STOP = "4"
MODE_WIZARD = "5"
MODE_RESET = "6"
MODE_CALIBRATE = "7"
MODE_DEBUG = "8"
MODE_STARTUP = "9"
MODE_SAFEMODE = "10"

# Mode Names for UI
MODE_NAMES = {
    MODE_AUTOMATIC: "Automatic",
    MODE_FREE_COOLING: "Free Cooling", 
    MODE_BOOST: "Boost",
    MODE_ABSENCE: "Absence",
    MODE_STOP: "Stop",
    MODE_WIZARD: "Wizard",
    MODE_RESET: "Reset", 
    MODE_CALIBRATE: "Calibrate",
    MODE_DEBUG: "Debug",
    MODE_STARTUP: "Startup",
    MODE_SAFEMODE: "Safe Mode"
}

# Sensor Types
SENSOR_TYPE_ABSENT = 1
SENSOR_TYPE_PYRO = 2
SENSOR_TYPE_CO2 = 3

SENSOR_TYPE_NAMES = {
    SENSOR_TYPE_ABSENT: "Absent",
    SENSOR_TYPE_PYRO: "Humidity", 
    SENSOR_TYPE_CO2: "CO2"
}

# Max number of ducts/rooms
MAX_DUCT = 10